pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: gcc
  steps:
  - script: sudo apt-get install -y ninja-build
    displayName: Dependencies
  - script: cmake test -G Ninja -DBUILD_CPP_TESTS=ON -DCMAKE_C_FLAGS='-march=native' -DCMAKE_CXX_FLAGS='-march=native'
    displayName: Configure
  - script: ninja -v
    displayName: Build
  - script: ./run-tests
    displayName: Tests
  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload to codecov.io'

- job: mipsel
  steps:
  - script: sudo apt-get -y install qemu-user
    displayName: APT Dependencies
  - script: |
      docker pull dockcross/linux-mipsel
      docker run --rm dockcross/linux-mipsel > ./dockcross-linux-mipsel
      chmod u+x ./dockcross-linux-mipsel
    displayName: Prepare Dockcross
  - script: ./dockcross-linux-mipsel cmake test -DBUILD_CPP_TESTS=ON
    displayName: Configure
  - script: ./dockcross-linux-mipsel make VERBOSE=1
    displayName: Build
  - script: ./dockcross-linux-mipsel ./run-tests
    displayName: Tests
  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload to codecov.io'
