[build]
  publish = 'web'
  command = 'mkdir -p web/amalgamated/x86 && cd simde && for header in x86/*.h; do ../amalgamate.py "$header" > ../web/amalgamated/"$header"; done'

[[headers]]
  for = "/amalgamated/x86/*.h"
  [headers.values]
    Access-Control-Allow-Origin = "*"
